[package]
name = "snippets"
version = "0.1.0"
authors = ["Toshinori Tsugita <tsugita.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-snippet = "0.2.8"
